import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Gnb from '@/components/layouts/Gnb';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="h-full w-full">
        <main className="sm:w-full md:w-[500px] m-auto h-full min-h-full flex flex-col relative bg-white">
          <Gnb />
          {children}
        </main>
      </body>
    </html>
  );
}
